version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install -U awscli
      - pip install -U sagemaker
      - pip install huggingface-hub

  build:
    commands:
        # Export the staging and production configuration files
        - |
          python build.py \
            --aws-region $AWS_REGION \
            --default-bucket $ARTIFACT_BUCKET \
            --model-execution-role $MODEL_EXECUTION_ROLE_ARN \
            --sagemaker-project-id $SAGEMAKER_PROJECT_ID \
            --sagemaker-project-name $SAGEMAKER_PROJECT_NAME \
            --export-staging-config $EXPORT_TEMPLATE_STAGING_CONFIG \
            --sagemaker-project-arn $SAGEMAKER_PROJECT_ARN \
            --inference-transformers-version 4.26 \
            --inference-framework-version 1.13 \
            --inference-python-version py39 \
            --inference-instance-type ml.g5.2xlarge

        # Package the infrastucture as code defined in endpoint-config-template.yml by using AWS CloudFormation.
        # Note that the Environment Variables like ARTIFACT_BUCKET, SAGEMAKER_PROJECT_NAME etc,. used below are expected to be setup by the
        # CodeBuild resrouce in the infra pipeline (in the ServiceCatalog product)
        - aws cloudformation package --template endpoint-config-template.yml --s3-bucket $ARTIFACT_BUCKET --output-template $EXPORT_TEMPLATE_NAME

        # Print the files to verify contents
        - cat $EXPORT_TEMPLATE_STAGING_CONFIG

artifacts:
  files:
    - $EXPORT_TEMPLATE_NAME
    - $EXPORT_TEMPLATE_STAGING_CONFIG
