Description:
  This template is built and deployed by the infrastructure pipeline in various stages (staging/production) as required.
  It specifies the resources that need to be created. In this case, an EventBridge Rule, a SageMaker Pipelines and a
  SageMake Model.
Parameters:
  EndpointName:
    Type: String
    Description: SageMaker Endpoint Name used by the lambda function
  LambdaPath:
    Type: String
    Description: S3 path for lambda artifact
  ModelExecutionRoleArn:
    Type: String
    Description: Execution role used for deploying the model.
  S3BucketArtifacts:
    Type: String
    Description: S3 bucket for artifacts
  SageMakerProjectName:
    Type: String
    Description: Name of the project (lower case)
    MinLength: 1
    MaxLength: 32
    AllowedPattern: ^[a-z](-*[a-z0-9])*
  SageMakerProjectId:
    Type: String
    Description: Id of the project
    MinLength: 1
    MaxLength: 32
  StageName:
    Type: String
    Description:
      The name for a project pipeline stage, such as dev or prod, for
      which resources are provisioned and deployed.

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Multi-Language-GenAI
      Timeout: 900
      PackageType: Zip
      Code:
        S3Bucket: !Ref S3BucketArtifacts
        S3Key: !Ref LambdaPath
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT: !Ref EndpointName
      Handler: lambda.handler.lambda_handler
      Runtime: python3.9
      Role: !Ref ModelExecutionRoleArn